apiVersion: v1
kind: Pod
metadata:
  name: config-pod-volume
spec:
  containers:
    - name: config-pod-volume
      image: volivattamchn/k8sdemos
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: config-map-demo-service
         
